name: Creation of OS installers
env:
  INNO_VERSION: 6.2.1

run-name: Creation of OS installers
on: [push]
jobs:
  Create-Windows-Installer:
    runs-on: windows-latest
    steps:
      - run: echo "The branch where this action it is running is ${{ github.ref }}."
      
      - name: Check out repository code
        uses: actions/checkout@v3.3.0
        
      - run: echo "The branch where this action it is running is ${{ github.ref }}."
      
      - name: Downloading Inno Setup installer
        run: curl -L -o inno_installer.exe http://files.jrsoftware.org/is/6/innosetup-${{ env.INNO_VERSION }}.exe
        
      - name: Running Inno Setup installer
        run: ./inno_installer.exe /verysilent /norestart /allusers /dir=installaters
        
      - name: Getting Flutter action
        uses: subosito/flutter-action@v2.8.0
        
      - name: Checking if Flutter it is installed
        run: flutter --version
        
      - name: List directory
        run: dir
        
      - name: Adding Windows support to flutter project.
        run: flutter config --enable-windows-desktop
        
      - name: Adding support to Linux, MacOS and Windows platforms.
        run: flutter create --platform=windows,macos,linux .
        
      - name: Build windows app with flutter
        run: flutter build windows
        
      - name: Create Windows Installer
        run: iscc installers_scripts/windowsScript.iss
        
      - name: Commit and push changes
        run: |
          git config --global user.name "LuisSS20"
          git config --global user.email "luissoriano@correo.ugr.es"

          git add installers/*
          git commit -m "Add new windows installer"
          git push
        
      - name:  Upload a Build Artifact with the windows installer compiled
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Installers
          path: installers/
