name: Creation of OS installers
env:
  INNO_VERSION: 6.2.1

run-name: Testing github action
on: [push, pull_request]
jobs:
  Create-Windows-Installer:
    runs-on: windows-latest
    steps:
      - run: echo "The branch where this action it is running is ${{ github.ref }}."
      
      - name: Check out repository code
        uses: actions/checkout@v3.3.0
        
      - run: echo "The branch where this action it is running is ${{ github.ref }}."
      
      - name: Downloading Inno Setup installer
        run: curl -L -o inno_installer.exe http://files.jrsoftware.org/is/6/innosetup-${{ env.INNO_VERSION }}.exe
        
      - name: Running Inno Setup installer
        run: ./inno_installer.exe /verysilent /norestart /allusers /dir=installaters
        
      - name: Getting Flutter action
        uses: subosito/flutter-action@v2.8.0
        
      - name: Checking if Flutter it is installed
        run: flutter --version
        
      - name: List directory
        run: dir
        
      - name: Build windows app with flutter
        run: flutter build windows
        
      

    
